dubai: Drop unused modules
* Also fixes

ERROR: lzo-rle.ko was not found in the kernel modules intermediates dir
Module load list must be corrected.
ERROR: lzo_compress.ko was not found in the kernel modules intermediates dir
Module load list must be corrected.
ERROR: lzo_decompress.ko was not found in the kernel modules intermediates dir
Module load list must be corrected.
ERROR: lzo.ko was not found in the kernel modules intermediates dir
Module load list must be corrected.
ERROR: zram.ko was not found in the kernel modules intermediates dir
Module load list must be corrected.

Change-Id: I0ad0bf593dcff27673de7ef1aa97c12002fe84f8